
#error_log logs/error.log;
#error_log logs/error.log  notice;
#error_log logs/error.log  info;
#pid        logs/nginx.pid;
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location /app-authors/ {
            proxy_pass http://authors-app/;
        }

        location /app-books/ {
            proxy_pass http://books-app/;
        }
    }