#CREAR IMAGEN
#docker build -f src/main/docker/Dockerfile.jvm -t app-authors .
#docker build -f src/main/docker/Dockerfile.jvm -t jordifpau/app-authors
#docker login
FROM docker.io/eclipse-temurin:25.0.3_9-jre-alpine
RUN mkdir /app
WORKDIR /app

COPY build/quarkus-app/lib ./lib
COPY build/quarkus-app/quarkus ./quarkus
COPY build/quarkus-app/app ./app
COPY build/quarkus-app/quarkus-run.jar app.jar

CMD ["java" , "-jar", "app.jar"]
